### ISSUE TITLE
Pulling speaker profiles from external source

### ISSUE THREAD

**Issue by keathley** [chadev/lunch-slides#13]
Is there a clever way that we can pull the speakers profile in over some sort of ajax or something.  I was trying to avoid making changes to this repo every week but I'm not sure that there is a way to avoid making weekly changes somewhere.  Maybe we just need to pull it by date?  I'm open to suggestions.

**Comment by juzten** [comment]
Maybe a json file hosted somewhere. That way we can just update the json file and have the site pull in the json file and display X amount of profiles from the file.

**Comment by StrangeWill** [comment]
> Maybe a json file hosted somewhere.

Doesn't that just mean we have to maintain a file either outside of all repos, or in another repo? Doesn't really resolve the problem, might as well keep it in-repo.

Not familiar with Meetup for managing events, but is there a way to tag people as presenters of certain meetups, and have it all data driven from Meetup's APIs (along with listing new meetups)?

Additionally maybe speaker profiles should just come from our development page?

**Comment by StrangeWill** [comment]
Nix the Meetup idea, doesn't support that, don't like how we'd have to consume their API either.

**Comment by keathley** [comment]
@juzten I thought about using a separate repo but like @StrangeWill said then wed just be updating that repo.  Meetup is definitely not going to be helpful.

@StrangeWill Do you mean the developer list on the main site?

**Comment by StrangeWill** [comment]
@keathley Yeah, figure keep all the information for a developer in one place, probably put more data to be stored that only shows when we're displaying a profile for a speaker and their event.

Of course that depends on if we will have non-developer speakers...

**Comment by keathley** [comment]
Starting in the new year I think we're going to have more non developer speakers (at least ones that are local).  Maybe we _do_ need a presenters repo or list with a date somewhere.

**Comment by juzten** [comment]
So you're saying they won't have dev profiles since they are non devs
correct? Since we can't pull from meetup there's not much we can do besides
update a list or hard code in a  speaker page.

**Comment by keathley** [comment]
The other option is the one that we've been talking about for a while: Just build our own meetup.  Is the list of things that we want big enough to warrant doing that now?

**Comment by kylegordy** [comment]
@keathley Not sure if it's big enough to warrant it yet, but it would be awesome if we did :+1: I mean we can always grow into it.
