### ISSUE TITLE
Increase font size for urls

### ISSUE THREAD

**Issue by colinrymer** [chadev/lunch-slides#24]
The meetup links are hard to read when you're not up close to the screen.

**Comment by colinrymer** [comment]
Bumping this be even in second row, urls are pretty small. @keathley or @kylegordy what's the resolution of the projector?

**Comment by kylegordy** [comment]
@colinrymer Umm, I'm not exactly sure. It's pretty low. If I had to guess somewhere around 1280 x 800.
