### ISSUE TITLE
Other (potential) slides

### ISSUE THREAD

**Issue by keathley** [chadev/lunch-slides#5]
These are just some things that I think would be good to add (some of these may exist).
- [x] Other meetups
  - [x] CodeXX
  - [x] NoogaJS
  - [x] Google Dev Group
  - [x] Drupal group
  - [x] Ruby Group
  - [x] Python Group
  - [x] .Net group (is this even a thing)
  - [x] Chadoop
  - [x] Open data group
  - [x] PHP Group
- [x] This Github org so others can get involved
- [ ] Some sort of first time visitor outreach thing
- [x] IRC
- [x] The meetup page

Any other ideas?

**Comment by kylegordy** [comment]
This sounds like a great start to me :+1:

**Comment by keathley** [comment]
What would you think about a who's hiring slide?  I'm not sure how much I love that idea but I figured I would ask.

**Comment by vendion** [comment]
That sounds like it could get messy/a pain to try and keep up with.  If
that were to happen you may want to age off things fairly quickly.

**Comment by keathley** [comment]
Yeah that was one of my concerns.  I'm not sure thats a feature that the community needs or if that would just be good for our sponsors.  I'm willing to manage it if the community needs it.  I'm not sure about it so  I figured I would give everyone else a chance to have an opinion.

**Comment by kylegordy** [comment]
Hmm, I could see something like this living in Chadev somewhere. Not sure that place is on our opening slides though. I think we should try to keep our intro slides as short and simple as possible, so we don't take too much time away from the talk. What do you all think?

**Comment by keathley** [comment]
agreed.  I think I might be getting ahead of myself.  I was thinking it might be kinda cool to have a few rotating slides at the beginning while people are mingling and such.  Stuff with the sponsors on it and things like that.  This page would be in there.  I don't think we should take any time during the presentation on it.  We can table it for now if y'all want.

**Comment by vendion** [comment]
I like the idea of of having some slides rotating while we are waiting for things to get started.  Like making the IRC channel, Subreddit, This GitHub Org, Sponsors rotating information.  Maybe a list of other groups in town, but we should still go over them at the start or end of the lunch as that is still a fundamental part of what Chadev is.

**Comment by keathley** [comment]
Yeah.  Ok so for now I'm going to work building the core slides.  We can tweak it as we go.

**Comment by keathley** [comment]
I've updated the list of other meetups.  I know that I missed a bunch.  Can y'all help fill in here a bit?

**Comment by keathley** [comment]
@acedrew do we have a full list of sponsors?

**Comment by vendion** [comment]
Not sure if .Net group or BeerJS is still active... also added in PHP group.

**Comment by juzten** [comment]
The .Net group is still active..[see this](http://www.chadnug.com/)
Their next meeting is November 11th

**Comment by juzten** [comment]
Code & Creativity
Lambda Lounge

**Comment by keathley** [comment]
@kylegordy do you have a preference on some sort of font icons or something?  I need a github and twitter icon for presenters

**Comment by keathley** [comment]
#6 Should fix most of this.  Closing for now.

**Comment by kylegordy** [comment]
@keathley Hows about the [twitter icon](https://github.com/chadev/chadev.github.io/blob/master/assets/images/icons/twitter-icon.svg) in the Chadev site repo? Here's a [Github icon](http://iconmonstr.com/github-icon) that matches it pretty well. Not sure we need a whole font or not. What do you think?

**Comment by keathley** [comment]
I don't think we need a font. We only have the two icons. 

Chris Keathley

**Comment by kylegordy** [comment]
Agreed, seems like a huge waste.
