### ISSUE TITLE
New slide to explain what chadev and lunch is

### ISSUE THREAD

**Issue by keathley** [chadev/lunch-slides#7]
I'd like to include a slide at the beginning that says what chadev is about (conglomerate of other meetups with designers and developers, etc.).  What do y'all think about this and what should be in this slide?

**Comment by vendion** [comment]
For the most part I think if we tweak this paragraph from the chadev.github.io site it should help explain what Chadev is.

Chadev tracks nearly thirty events per month that pertain to the developer/tech community. ~~We are in the process of increasing the reach of our brand, while simultaneously~~ ~~supporting~~  We support the growth of smaller sub communities for the various specific languages and interest groups. Our hope is to continue to support and promote the developer community, while maintaining an open and inclusive entry point for new people to the community.

That should give a decent start, at the same time I'm no copy writer either :smile:

**Comment by kylegordy** [comment]
@vendion Sounds like a great start to me :smile:
